# Generated by Django 3.1.1 on 2020-09-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(help_text='Enter your name', max_length=20)),
                ('image', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(help_text='Enter give a description', max_length=500)),
            ],
        ),
    ]
